# Generated by Django 5.1.1 on 2024-10-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('photobook', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('photoauthor', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d/author')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('retal_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retal_period', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('state', models.CharField(choices=[('available', 'available'), ('sold', 'sold'), ('rental', 'rental')], max_length=50, null=True)),
                ('typebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
        ),
    ]
