# Generated by Django 5.1.1 on 2024-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_total_retal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_retal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
